# Generated by Django 4.2 on 2024-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('cuit', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cosechadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tractores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.IntegerField()),
                ('fecha_de_venta', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
